---
title: "Abby’s code"
output: html_document
---


# import data
```{r, warning=FALSE, error=FALSE, echo=FALSE, message=FALSE}
library(tidyverse) 
library(macleish)
library(sp)
library(leaflet)
library(rgdal)
# install.packages("tmap")
library(tmap)
library(raster)
library(rgeos)
library(ggthemes)
library(RColorBrewer)
names(macleish_layers)

summary(macleish_layers)
```


```{r}
url <- "http://wsgw.mass.gov/data/gispub/shape/state/contours250k.zip"
download.file(url, destfile = basename(url))
unzip("contours250k.zip",exdir="contour")

elevation1 <- path.expand("contour")
list.files(elevation1)

ogrListLayers(elevation1)
ogrInfo(elevation1, layer = "CONTOURS250K_ARC")

elevation2 <- readOGR(elevation1, "CONTOURS250K_ARC")

# str(elevation2, max.level=2)
# plot(elevation2)
```
# verify the same proj4string
```{r}
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

proj4string(macleish_layers[["trails"]])
proj4string(elevation2)

# transform to have aea's proj4string
elevation2 <- spTransform(elevation2, proj4_aea)
macleish_layers[["boundary"]] <- spTransform(macleish_layers[["boundary"]], proj4_aea)
macleish_layers[["trails"]] <- spTransform(macleish_layers[["trails"]], proj4_aea)
```


```{r}
# elevation 
mac_elevation <- gIntersection(macleish_layers[["boundary"]], elevation2)

mac_elevation <- spTransform(mac_elevation, CRS("+init=epsg:4326"))
macleish_layers[["trails"]] <- spTransform(macleish_layers[["trails"]],CRS("+init=epsg:4326"))
macleish_layers[["boundary"]] <- spTransform(macleish_layers[["boundary"]],CRS("+init=epsg:4326"))


# length of trails
trail_lengths <- SpatialLinesLengths(macleish_layers[["trails"]], longlat = TRUE)
trail_lengths
```

```{r}
trails <- data.frame(trail_lengths)

trails <- cbind(trails, "conversion")

trails %>%
  rename(km = `0`,
         conversion = `"conversion"`) %>%
  mutate(km = 0.621371, 
         conversion = km*trail_lengths) 

```



```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = mac_elevation, weight =3, color="white", dashArray="white") %>%
  addPolylines(data=macleish_layers[["trails"]], weight = 5, color=~color, popup=~name) %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite")

leaflet(macleish_layers[["trails"]]) %>%
   addLegend(pal=~color, values = ~name)


trails_elevation <- gIntersection(macleish_layers[["trails"]], mac_elevation)

str(macleish_layers[["trails"]]@data, max.level = 2)
addPolylin

str(macleish_layers[["trails"]])


```




